server {
    listen 80;
    root /usr/share/nginx/html;

    location = / {
        return 301 /rm1210/;
    }

    location /rm1210 {
        try_files $uri $uri/ $uri.html /rm1210/index.html;
    }
}
